irc3/__init__.py, irc3/rfc.py
An example plugin using the invite command and event:
```python
import irc3
from irc3 import rfc
from irc3.plugins.command import command
@irc3.plugin
class Test:
requires = [
'irc3.plugins.core',
'irc3.plugins.command',
]
def __init__(self, bot):
self.bot = bot
self.log = self.bot.log
@irc3.event(rfc.INVITE)
def on_invite(self, mask, channel):
self.bot.join(channel)
self.bot.loop.call_later(2, self.bot.privmsg, channel, "Thanks %s !" % mask.nick)
@command
def invite(self, mask, target, args):
"""
Invite a user to the current channel
%%invite <nick>
"""
self.bot.invite(args['<nick>'], target)
```
=> added invite command and event

examples/mybot.py
The configuration of the logging module happens here: <https://github.com/gawel/irc3/blob/master/irc3/base.py#L75>. This can lead new users to think they can set a custom logging configuration before instanciate the bot, but I think dictConfig() overrides the previous calls.
=> unnecessary logging

CHANGES.rst, irc3/plugins/storage.py
* irc.plugins.storage: `db['foo']` now will raise a `KeyError` if the key does
not exist to match dictionary behaviour.
* irc.plugins.storage now supports `db.get(key)`  that will return either `None`
or the value of an optional `default` argument.
=> Change storage to be more like python dict objects

irc3/plugins/command.py
So we can use both `!help !foo` and `!help foo` (given `!` as the command prefix).
=> Strip out self.context.config.cmd from !help arg

irc3/plugins/userlist.py
Users were never removed upon being devoiced or deopped because of an incorrect check in the mode event. Should be checking tgt instead of target.
=> Fixes bug in userlist plugin

docs/plugins/casefold.rst, irc3/plugins/casefold.py
By default `irc3` doesn't do any casefolding on nicks/channels/etc. This can create issues in things like the `userlist` plugin where channels are seen as different where they should be the same, accessing user nicks can be problematic, etc.
I've made this a core plugin rather than putting it in `irc3_plugins` because I think the core should be casefolding things like its data structures, the `userlist` plugin, etc.
**Note:** This is an in-progress PR, I'm planning to make the `userlist` plugin use this by default.
=> Casefold regarding the IRC server's casemapping

irc3/plugins/command.py
Allows to use guards which are marked with `@asyncio.coroutine`. Without this test, coroutine guards with commands that aren't async fail.
=> Allow to use coroutine guards

irc3/plugins/command.py, tests/test_commands.py
Currently the command `!help ` will get ignored because the trialing
space isn't allowed in the command regexp.
=> Don't reject commands with trailing spaces

examples/mycommands.py, irc3/plugins/command.py, tests/test_commands.py
Because sometimes you don't want your average user to start trying out !quit (even though he will probably not be able to run it).
=> Allow to hide commands from !help

irc3/plugins/storage.py
iterating over kwargs isn't a great idea if you don't check if the key exists.
=> Prevent keyerror when setting keys that don't exist.

.gitignore
Dunno where it exactly came from, but I suddenly had a `.cache` folder after running tox.
Also added .ropeproject to the ignore rules for rope users
=> Ignore cache directory created by testing tools

irc3/plugins/command.py
Currently, !help doesntexist gets dropped silently. This improves that. I also
added a bit of documentation (and thus testing).
=> Add !help nonexistant error message

examples/mybot.py, examples/mybot_plugin.py, examples/nickserv.py, irc3/base.py, irc3/plugins/command.py, irc3/plugins/human.py, irc3/plugins/logger.py, irc3/rfc.py, irc3/tags.py, irc3/template/plugin.py
This is not a patch to fully implement and integrate the specification for IRCv3.2 tags. It just adds basic support to accept and parse messages that happen to contain tags. With this patch it is possible to manually send CAP REQ messages and successfully get tagdata afterwards.
For IRCv3.2 tag specification see http://ircv3.net/specs/core/message-tags-3.2.html
~~Sadly, this brings some minor backwards-incompatibilities, since the additional field "tags" is added to all events, including some JOIN events that did not take kwargs before.~~
Edit: See comments below.
I suggest always including kwargs in all events anyway, to be able to add more fields in the future without such problems.
An example on how this enables the use of tags for twitch irc:
- Sent CAP REQ messages before joining any …
=> added basic support for IRCv3.2 tags

irc3/plugins/core.py, tests/test_bot.py, tests/test_commands.py
Some servers send the a PING argument with spaces so we need to ensure we send the response as a trailing arg. Additionally, I changed the PING to use the trailing arg as well, just in case.
=> Ensure we send the PING and PONG data as trailing

irc3/tags.py, irc3/utils.py
Just some sugar to make accessing IRCv3.2 tags a little more intuitive, mostly to avoid the import of "irc3.tags". I should have added something like this in the first pull request, but I didn't, so that's that.
Before (still valid):
```
@irc3.event(irc3.rfc.PRIVMSG)
def on_privmsg(self, tags=None, **kw):
tagdict = irc3.tags.decode(tags)
print(tagdict)
```
After:
```
@irc3.event(irc3.rfc.PRIVMSG)
def on_privmsg(self, tags=None, **kw):
tagdict = tags.tagdict if tags else {}
print(tagdict)
```
Also added some error checking for decoding tags, since people could potentionally try to parse every IrcString as tags now.
=> Added tagdict property to IrcString, improved tag parsing

irc3/plugins/command.py
My bot actually uses + as prefix.
Though, why not use `re.escape(...)` instead?
=> add + to WEIRD_CHARS

irc3/plugins/async.py
The variable name `context` was used but the bot was being passed in as `bot`.
=> Fix a typo in the Async docs

irc3/plugins/async.py
Add multi: True to the dictionary so it doesn't get removed.
=> WHOIS may return multiple channel lines

irc3/plugins/command.py, tests/test_commands.py
Current command plugin have issue with parsing command that have couple spaces between command and arguments. For example:  `!cmd_arg argument` will work, but this: 
!cmd_arg   argument
will not.
=> Fix bug with command arguments and spaces

irc3/plugins/autojoins.py, irc3/template/config.ini, tests/test_autojoins.py
Sometimes it's useful to delay autojoin. For example: if you want to hide your host and apply special modes before join or for authorization before join. This can be better accomplished by calling join after receiving event that all required tasks like authorization or changing mode were successfully done, but since this is highly network dependent thing, it is good to have autojoin delay.
Many popular irc clients support autojoin delay: [weechat](https://weechat.org/files/doc/weechat_faq.en.html#irc_sasl), [mIRC](http://en.wikichip.org/wiki/mirc/commands/autojoin), [hexchat](https://github.com/hexchat/hexchat/blob/c874a9525c9b66f1d5ddcf6c4107d046eba7e2c5/src/common/cfgfiles.c#L510), xchat and many others.
This patch adds configure option `autojoin_delay` that delays joining  for …
=> Add autojoin_delay configuration option

irc3/testing.py
If tests were called from another directory they can crash because of using relative paths. This patch makes path absolute.
=> Fix tests error when they called from another dir

irc3/plugins/autojoins.py, tests/test_autojoins.py
With this patch it is possible to update autojoin channels via reloading bot (sending hup signal). Code also will handle event when bot was reloaded before autojoin begin to work (in case it was delayed).
=> Handle reload in autojoins plugin

irc3/base.py
Here's some note from docopt docs:
> Note, when docopt is set to automatically handle -h, --help and --version options, you still need to mention them in usage pattern for this to work. Also, for your users to know about them.
=> Add --help and --version CLI options

irc3/plugins/fifo.py
`listdir` have no guarantees about order of items. This causes an exceptions during execution of unit tests under some versions of python. Using `sorted` function solves this issue.
=> Fix doctest in fifo plugin

irc3/plugins/fifo.py, tests/test_fifo.py
Original code of fifo plugin have couple issues. First of all, it is using polling with 0.2 seconds interval for checking or FIFO available for read. For one channel it will produce 5 system calls (1 / 0.2) per second. It looks like small amount of work, but let's imagine that bot joins to 19 channels. This means that it will execute 100 system calls per second (19 channels + 1 for :raw, 20 * 5 = 100). More channels will cause more load. Instead of polling I'm using event driven approach, handler are called only when new data available in fifo.
There are also another issue, POSIX recommends using  `O_NONBLOCK` over `O_NDELAY`. Here's one of explanations [why](https://mail.python.org/pipermail/python-list/1999-May/013687.html). Same recommendations came from  [Richard Stevens …
=> Couple improvements to fifo plugin

.coveragerc
On one of my working machines I had an interesting issue.  Coverage wasn't generating report for this project. Result was like this: 
```
Coverage.py warning: No data was collected.
py34 runtests: commands[3] | coverage report -m
Name    Stmts   Miss  Cover   Missing
-------------------------------------
No data to report.
ERROR: InvocationError: '/home/slava/src/irc3/.tox/py34/bin/coverage report -m'
___________________________________ summary ____________________________________
ERROR:   py34: commands failed
```
After some time, I found that issue was caused by `*/src*` rule in `.coveragerc` file. This happened because I used `~/src/irc3/` folder and any file was matching to that rule.  Same issue might be caused by `*/tests*` rule too.
=> Fix issue with no coverage report

setup.cfg, setup.py
This commit will allow executing tests via `python setup.py test` command. Also this command will install all necessary packages for tests.
=> Run tests on calling setup.py test

docs/plugins/autocommand.rst, irc3/plugins/autocommand.py, tests/test_autocommand.py
Hi, I made plugin about what we were talking in issue #99. I implemented `/sleep` command with slash prefix, because there are some possibility that some IRC might have such command (very small but still possible). Also, in case of need introducing other specially handled commands, slash prefix will be a sign of such commands.
=> Add autocommand module

irc3/base.py
As per https://docs.python.org/3/library/ssl.html#examples and https://docs.python.org/3/library/ssl.html#ssl.Purpose.SERVER_AUTH, the Purpose is supposed to mean the type of target we are connecting to, not the type of client/server we are.
=> Fix ssl context creation

irc3/plugins/storage.py
This commit adds automatic support for [ujson](https://pypi.python.org/pypi/ujson), a faster json implementation than the Python default. If ujson is installed in the user's site packages, it will automatically be imported as `json`, so no other code changes are necessary to benefit from it.
=> Add support for ujson to storage plugin

docs/plugins/quakenet.rst, irc3/plugins/quakenet.py, tests/test_quakenet.py
This plugin handles authorization on [QuakeNet IRC network](https://en.wikipedia.org/wiki/QuakeNet). It supports both [simple](https://www.quakenet.org/help/q-commands/auth) and [challenge based auth](https://www.quakenet.org/development/challengeauth). Challenge based authorization is used by default. 
Also, it can [hide your hostname](https://www.quakenet.org/help/security/how-can-i-hide-my-hostname-on-quakenet) after authorization.
=> Add quakenet plugin

irc3/plugins/autocommand.py, tests/test_autocommand.py
Renamed config-directive to `autocommands` and reworded documentation a little bit.
=> [autocommand] Rename and document config-directive

irc3/rfc.py
This avoids stripping or rejecting events when the text after the `:`
marker starts with whitespace.
This causes issues when receiving messages starting with color codes
(i.e. `\x1D` for italics)
If we still want to strip leading whitespace, we'll need to use more specific sequences to avoid matching IRC control codes as whitespace.
=> Allow spaces at start of messages in RFC regexps

irc3/plugins/command.py, tests/test_irc3d.py
This fixes the parsing of irc3d PRIVMSG command
Some IRC control codes such as 0x1D (italic) are considered as
whitespace in unicode and they get converted to regular spaces.
Since RFC2812 states that only space (0x20) is considered whitespace,
only splitting by space seems reasonable.
=> commands: only consider space as whitespace

irc3/__init__.py, tests/test_bot.py
This PR adds a method ```action``` to the bot which sends a ```/me```.
=> Added method for sending /me

irc3/base.py
impliments the ability to bind a client to a specific address
example:
```
def main():
config = dict(
nick='irc3', autojoins=['#irc3'],
host='2001:19f0:5:8a4::1dc', port=6667, ssl=False, vhost='2001:470:e473::dead:beef',
includes=[
'irc3.plugins.core',
'irc3.plugins.command',
'irc3.plugins.human',
__name__,  # this register MyPlugin
]
)
bot = irc3.IrcBot.from_config(config)
bot.run(forever=True)
```
=> working vhost support

irc3/base.py
The problem was that IrcBot.reload() passed the actual modules instead
of their names to IrcObject.include()
=> Fix plugin reloading working only every other time

.travis.yml, irc3/plugins/command.py, tests/test_commands.py, tox.ini
Added an option the `@command` decorator that prevent the bot from responding with "Invalid arguments." when a command is used incorrectly along with the test units to cover the new option.
example:
```python
@command(quiet=True)
def cmd(self, mask, target, args):
```
=> Ability to silence "Invalid arguments." response.

irc3/base.py, setup.py, tests/test_bot.py
This will allow for people to provide their own plugins and just be able to specify them by using entry_points in pkg_resources.
This is an example, that I have added a test for.
https://github.com/gtmanfred/irc3-plugins-test
Basically, you add an entry point for `irc3.loader` and then the name of the plugin points to what module should be loaded.
```
setuptools.setup(
name='irc3-plugins-test',
summary='test plugin for irc3',
version='0.0.3',
long_description=desc,
author='Daniel Wallace',
author_email='daniel@gtmanfred.com',
url='https://github.com/gtmanfred/irc3-plugins-test',
packages=['irc3_plugins_test',],
entry_points='''
[irc3.loader]
irc3.plugins.test = irc3_plugins_test.test
''',
)
```
=> load modules using pkg_resources

irc3/plugins/slack.py, tests/test_slack.py
I made a mistake at some point and simplified the storage down to just the name, since that is the only thing I needed about a user.
=> fix bug in slack plugin

irc3/plugins/social.py
Had this bug while trying to run alain locally without twitter credentials (not found on the server neither but it's another issue).
Still willing to try alain locally I expected the exception to log it instead of crashing.
=> Except a KeyError on missing twitter configuration

irc3/asynchronous.py
Otherwise, I had `WHOIS` fail for the nick `Tho[m]`.
=> Escape string that are interpolated into the regular expressions.

irc3/asynchronous.py, irc3/plugins/asynchronious.py, irc3/plugins/sasl.py, tests/test_async.py
- Fix use of deprecated function removed in Py39
- Correctly interpolate regexes in async queries (corrects #185)
=> Correctly interpolate regexes in async queries (corrects #185)

irc3d/plugins/userlist.py, tests/test_irc3d_userlist.py
Hi,
I guess some clients want to send multi-channel JOINs as `foo,bar,baz`, which I couldn't get the test server to accept. Sorry if I'm wrong and this PR is just nonsense.
Thanks!
P.S. I sent you an email about this last summer (apologies if that was annoying; I wasn't allowed to use GitHub back then).
=> Allow comma-separated chans in server userlist JOIN

conftest.py, irc3/_parse_rfc.py, irc3/_rfc.py, irc3/dec.py, irc3/plugins/asynchronious.py, irc3/plugins/autojoins.py, irc3/plugins/feeds.py, irc3/plugins/fifo.py, irc3/plugins/quakenet.py, irc3/rfc.py, irc3/tags.py, irc3/utils.py, tests/test_utils.py, tests/test_web.py
Happen that I got:
Wed, 15 Dec 2021 19:13:06 +0000
stored in my ~/.irc3/feeds/discuss.updated, the only way to get a new post is to have
one posted on a wednesday now :D
It would probably have been cleaner to keep the same format instead of having to use `isoformat` and parse it back, but feedparser's dateparser is prefixed by an underscore, so I prefer not to use it :p
While doing it I also spotted a small error in the datetime constructions: `datetime.datetime(*e.updated_parsed[:7])`, taking 7 elements takes the `tm_wday` (weekday) and use it as a microsecond, so I changed it to `[:6]`.
While I was there I fixed `tox -e flake8`, there were a few "unrecognized escape sequences" (a warning since Python 3.6 [that may become a SyntaxError in the …
=> feeds: All date formats can't be compared as strings.

irc3/plugins/feeds.py
Bonjour Gawel,
See: https://github.com/psf/requests/issues/2766
It may become thread-safe again in the future, but I don't think irc3 gets a good benefit of using `Session` objects, if I understand correctly it only allow connection pooling (and parameter sharing), but as irc3 only do HTTP requests every now and then, the connections are probably not recycled anyway (I bet they just timeout). If I'm true it's probably even nicer (for webservers) **not** using a `requests.Session`, so we close TCP connections right away instead of trying to keep them open for nothing.
(I don't like when I try to guess performances-related things, bad practice at its finest...)
`irc3` used `requests.Session` to configure the headers once for all, so I used a global constant instead.
There's other places in …
=> Spotted that requests session may not be thread-safe.

irc3/utils.py, tests/test_cron.py, tests/test_utils.py
=> Implement setting keys like `sasl_password` in `parse_config_env` and `${##}` in `parse_config`

tests/test_cron.py
The problem with `TestCron.test_callable` is that CronSim doesn't support seconds the way croniter does. The updated test passes, except you may have to wait up to a minute.
=> Fix `TestCron`

irc3/__init__.py, irc3/plugins/command.py, irc3/utils.py, irc3d/__init__.py, tests/test_utils.py
This PR implements a new `utils` function `split_message_byte_len(message, max_bytes, encoding, prefix='')`. The function splits a string into a list of string chunks, each chunk up to `max_bytes` bytes. It ensures IRC messages stay under their byte limit.
The fact the function ~~returns `list[str]`~~ yields `str` makes it easy to replace existing uses of `split_message`. I tried returning `bytes`, and it required more thorough modification of the `split_message` call sites. For example, you had to replace string literals with byte literals and add checks like the following to `write` functions:
```none
if not isinstance(data, bytes):
data = data.encode(self.encoding)
```
It seems best to avoid this; Python programmers normally work with strings.
We only split on spaces and preserve other …
=> Split long messages based on byte length

irc3/plugins/shell_command.py
The mask/nickname is a useful info for the command, pass it down via an envvar.
=> shell_command plugin: pass IRC mask to the command via env_var
