irc3/__init__.py, irc3/rfc.py
This add the ability to change and detect a modification of the topic in a channel. This also add the ability to mark ourself as away / no longer away. I also fixed the code of my previous pull request to make it looks exactly like the rest of the file.
Plugin example for topic:
```python
import irc3
from irc3 import rfc
from irc3.plugins.command import command
@irc3.plugin
class MyPlugin:
requires = [
'irc3.plugins.core',
'irc3.plugins.command',
]
def __init__(self, bot):
self.bot = bot
@irc3.event(rfc.TOPIC)
def on_topic(self, mask, channel, data):
msg = '%s has changed the topic to: %s' % (mask.nick, data)
self.bot.privmsg(channel, msg)
@irc3.event(rfc.RPL_TOPIC)
def on_join_topic(self, srv, me, channel, data):
self.bot.log.info('[%s] The topic of %s is: %s' % (srv, channel, data)) …
```
=> add TOPIC and AWAY command/event

tests/test_commands.py
=> Add a test for 7513ffe (help command with bang)

irc3/plugins/async.py
=> Accounts is with two Cs

irc3/plugins/command.py, irc3d/plugins/command.py, tests/test_commands.py
But introduce a configuration flag to turn this off
=> Make commands case insensitive

tests/test_casefold.py
Add a basic little testcase for the `casefold` plugin.
=> Add testcase for casefold plugin

irc3/__init__.py
Seems this was missed. Worked for me after I made this change.
=> need to pass host and ip to dcc

irc3/template/plugin.py
Alternatively, we could put the channel name there.
=> Remove the unneeded %s from the template plugin

CHANGES.rst, irc3/__init__.py, irc3/template/config.ini
https://github.com/gawel/irc3/issues/96
=> Fix rate control sending an extra line (fixes #96)

irc3/base.py
=> Stay consistent with local variables usage

irc3/__init__.py
Did not find any reason for PRIVMSG to not pass nowait.
=> Fix missing nowait

irc3/plugins/userlist.py, irc3d/plugins/userlist.py, tests/test_irc3d_userlist.py
avoid duplicated usage of nicknames
=> Duplicated nicks

irc3/plugins/userlist.py, irc3d/plugins/userlist.py, tests/test_irc3d.py, tests/test_irc3d_userlist.py, tests/test_reconn.py
This fixes several issues with irc3d
=> irc3d fixes

irc3/plugins/async.py, tests/test_async.py
Extends the bot's who command with modes for channels. Implemented using dynamic classes as discussed on IRC.
Tests not implemented at this point.
=> Add support for WHO command on channels with modes

irc3/plugins/async.py, tests/test_async.py
Event seems not correct, at least there's an empty dict in the results (workaround included). Hints?
=> Added async command to receive channel bans

irc3/plugins/async.py, tests/test_async.py
Adds ans async CTCP message, result contains mask, ctcp and reply.
=> Async CTCP

irc3/plugins/async.py, tests/test_async.py
=> Undo accidential deletion of async.ChannelBans

irc3/plugins/async.py, tests/test_async.py
Added and error event, for example for umode +R:
`:server 486 nick :You must identify to a registered nick to private message mrhanky`
=> Added an error event to async ctcp

README.rst, irc3/plugins/slack.py, tests/test_slack.py
This implements a ping function, which will keep track of if the
websocket is alive.  It also moves over to using asyncio.wait, so that
when the ping coroutine exits, it will restart the whole slack portion
of the bot to reconnect slack
=> implement ping function for slack plugin

irc3/utils.py, tests/test_utils.py
Let me know if you'd like a different way of splitting the host. I tried to follow how you parsed `nick`.
=> IrcString: Retrieve username/hostname from mask

irc3/plugins/userlist.py
=> Use pop() in all relevant places.

.github/workflows/tox.yml, irc3/compat.py, tox.ini
=> Fix python 3.10 compatibility issues
